spring:
  application:
    name: mainApp

  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always